const navScript=document.createElement('script');navScript.src='nav.js';document.head.append(navScript);
const headingScript=document.createElement('script');headingScript.src='program-overrides.js';document.head.append(headingScript);
const schedule=[['3:00 PM – 3:15 PM','Guest arrival & registration','Welcome dance music + photo wall'],['3:15 PM – 3:25 PM','Opening prayer & welcome remarks','A gentle start to our afternoon'],['3:25 PM – 3:35 PM','Entrance of the celebrant','Mariane'],['3:35 PM – 4:20 PM','Parlor games time!','Hosted by: __________________'],['4:20 PM – 4:30 PM','Food time & snack break','Little bites for hungry butterflies'],['4:30 PM – 4:40 PM','Birthday message, wish & cake cutting','Make a wish, Mariane!'],['4:40 PM – 5:00 PM','Giveaways & thank you message','A little thank-you for every guest'],['5:00 PM – 5:30 PM','Free play, bubbles & photo booth','The garden stays open for play']];
const games=[['01','Patintero relay','Cross the lines without being tagged. Two teams, two rounds, and a team prize.','2 teams of 5–6 kids'],['02','Pinoy Henyo','Guess the word on your head using YES/NO clues only. One minute per turn.','Pairs'],['03','Sack race','"Fly to the garden!" Hop to the cone and back, then tag the next teammate.','4–5 kids per heat'],['04','Musical chairs','Walk while the music plays. When it stops, sit fast. Last kid sitting wins.','All kids'],['05','Bring me','Bring something blue, something with wings, or two girls with hair ties.','All kids']];
const event=JSON.parse(localStorage.getItem('butterflyEvent')||'{}');
const currentSchedule=Array.isArray(event.schedule)?event.schedule:schedule; const currentGames=Array.isArray(event.games)?event.games:games;
document.getElementById('timeline').innerHTML=currentSchedule.map(([time,title,note])=>`<div class="timeline-item"><time class="schedule-time">${time}</time><div><strong class="schedule-title">${title}</strong><p class="schedule-description">${note}</p></div></div>`).join('');
document.getElementById('gameGrid').innerHTML=currentGames.map(([number,title,description,players])=>`<article class="game-card"><span>GAME ${number}</span><h3>${title}</h3><p>${description}</p><small>PLAYERS · ${players}</small></article>`).join('');
document.getElementById('downloadProgram').addEventListener('click',()=>window.print());
